name: Firestore Rules Test

on:
  workflow_dispatch:
  push:
    branches: [ main, Church-On-App-with-Cursor ]
    paths:
      - 'church_on_app/firestore.rules'
      - 'church_on_app/test/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Start Firestore emulator
        working-directory: church_on_app
        run: |
          nohup firebase emulators:start --only firestore --project demo-test --import=.firebase_data --export-on-exit &
          sleep 5
      - name: Run tests against emulator
        env:
          FIRESTORE_EMULATOR_HOST: '127.0.0.1:8080'
          FIREBASE_AUTH_EMULATOR_HOST: '127.0.0.1:9099'
        working-directory: church_on_app
        run: |
          flutter pub get
          flutter test -r expanded