name: Build Android, iOS & Web

on:
  push:
    branches:
      - Church-On-App-with-Cursor
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [android, web]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2" # Adjust to match your project

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        if: matrix.platform == 'android'
        run: flutter build apk --release

      - name: Build Android AppBundle
        if: matrix.platform == 'android'
        run: flutter build appbundle --release

      - name: Build Web
        if: matrix.platform == 'web'
        run: flutter build web

      - name: Upload Android APK
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Android AAB
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload Web Build
        if: matrix.platform == 'web'
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
