name: Build and Deploy Flutter Web to Firebase Hosting

on:
  pull_request:
    branches:
      - cursor/build-church-on-app-with-all-features-1463  # Your PR branch
  push:
    branches:
      - Church-On-App-with-Cursor  # Your main branch to deploy live

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  build_and_deploy_preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'  # Pin your Flutter version

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            church_on_app/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('church_on_app/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get Flutter dependencies
        working-directory: church_on_app
        run: flutter pub get

      - name: Build Flutter Web (release)
        working-directory: church_on_app
        run: flutter build web --release

      - name: Deploy to Firebase Hosting (Preview)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHURCH_ON_APP }}
          projectId: church-on-app
          channelId: preview  # This is the secret sauce for preview deploys

  build_and_deploy_live:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            church_on_app/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('church_on_app/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get Flutter dependencies
        working-directory: church_on_app
        run: flutter pub get

      - name: Build Flutter Web (release)
        working-directory: church_on_app
        run: flutter build web --release

      - name: Deploy to Firebase Hosting (Live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHURCH_ON_APP }}
          projectId: church-on-app
          # no channelId means live production deploy

