name: Flutter Web Build and Deploy

on:
  pull_request:
    branches:
      - '**'  # All PR branches
  push:
    branches:
      - Church-On-App-with-Cursor

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:

  preview_deploy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            church_on_app/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('church_on_app/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get Flutter dependencies
        working-directory: church_on_app
        run: flutter pub get

      - name: Build Flutter Web (release)
        working-directory: church_on_app
        run: flutter build web --release

      - name: Deploy to Firebase Hosting Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHURCH_ON_APP }}
          projectId: church-on-app
          channelId: pr-${{ github.event.number }}

  live_deploy:
    if: github.event_name == 'push' && contains(github.ref, 'Church-On-App-with-Cursor')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            church_on_app/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('church_on_app/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get Flutter dependencies
        working-directory: church_on_app
        run: flutter pub get

      - name: Build Flutter Web (release)
        working-directory: church_on_app
        run: flutter build web --release

      - name: Deploy to Firebase Hosting (Live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHURCH_ON_APP }}
          projectId: church-on-app
