name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - Church-On-App-with-Cursor

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'   # upgrade to a Flutter version with Dart 3.4.3+

      - name: Build Flutter Web
        run: flutter build web --release
        working-directory: church_on_app

      - name: Deploy to Firebase Hosting (Live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHURCH_ON_APP }}
          channelId: live
          projectId: church-on-app
